package formularios;

import classes.Dados;
import classes.Ultilidades;
import javax.swing.table.DefaultTableModel;

public class frmPesqCliente extends javax.swing.JDialog {

    private Dados msDados;

    private DefaultTableModel mTabela;

    private String resposta = "";

    public String getResposta() {
        return resposta;
    }

    public void setDados(Dados msDados) {
        this.msDados = msDados;

    }

    private void preencherTabela() {

        String titulos[] = {"ID", "Nome", "S_nome"};
        String registro[] = new String[3];
        mTabela = new DefaultTableModel(null, titulos);
        if (txtpesqcli.getText().equals("")) {
            for (int i = 0; i < msDados.numeroCliente(); i++) {
                registro[0] = msDados.getCliente()[i].getIdCliente();
                registro[1] = msDados.getCliente()[i].getNome();
                registro[2] = msDados.getCliente()[i].getSNome();

            }

            tblTabela.setModel(mTabela);
            return;

        }
        if (radionome.isSelected()) {
            for (int i = 0; i < msDados.numeroCliente(); i++) {
                if (msDados.getCliente()[i].getNome().startsWith(txtpesqcli.getText())) {
                    registro[0] = msDados.getCliente()[i].getIdCliente();
                    registro[1] = msDados.getCliente()[i].getNome();
                    registro[2] = msDados.getCliente()[i].getSNome();

                    mTabela.addRow(registro);

                }
            }
            tblTabela.setModel(mTabela);
            return;
        }

        if (radiosnome.isSelected()) {
            for (int i = 0; i < msDados.numeroCliente(); i++) {
                if (msDados.getCliente()[i].getSNome().startsWith(txtpesqcli.getText())) {
                    registro[0] = msDados.getCliente()[i].getIdCliente();
                    registro[1] = msDados.getCliente()[i].getNome();
                    registro[2] = msDados.getCliente()[i].getSNome();

                    mTabela.addRow(registro);

                }
            }
            tblTabela.setModel(mTabela);
            return;
        }
        if (radioid.isSelected()) {
            for (int i = 0; i < msDados.numeroCliente(); i++) {
                if (msDados.getCliente()[i].getIdCliente().startsWith(txtpesqcli.getText())) {
                    registro[0] = msDados.getCliente()[i].getIdCliente();
                    registro[1] = msDados.getCliente()[i].getNome();
                    registro[2] = msDados.getCliente()[i].getSNome();

                    mTabela.addRow(registro);

                }
            }
            tblTabela.setModel(mTabela);

        }
    }

    public frmPesqCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //validando escola de radio button
        bgtipopesq.add(radioid);
        bgtipopesq.add(radionome);
        bgtipopesq.add(radiosnome);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopesq = new javax.swing.ButtonGroup();
        radioid = new javax.swing.JRadioButton();
        radionome = new javax.swing.JRadioButton();
        radiosnome = new javax.swing.JRadioButton();
        txtpesqcli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        btnpesqcli = new javax.swing.JButton();
        btnpesqsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        radioid.setSelected(true);
        radioid.setText("Id Cliente");
        radioid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioidActionPerformed(evt);
            }
        });

        radionome.setText("Nome");
        radionome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionomeActionPerformed(evt);
            }
        });

        radiosnome.setText("Sobrenome");
        radiosnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosnomeActionPerformed(evt);
            }
        });

        txtpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesqcliActionPerformed(evt);
            }
        });

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sobrenome"
            }
        ));
        tblTabela.getTableHeader().setResizingAllowed(false);
        tblTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTabela);

        btnpesqcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisa3.png"))); // NOI18N
        btnpesqcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqcliActionPerformed(evt);
            }
        });

        btnpesqsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir-produto.png"))); // NOI18N
        btnpesqsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesqsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpesqcli)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(radioid)
                        .addGap(44, 44, 44)
                        .addComponent(radionome)
                        .addGap(46, 46, 46)
                        .addComponent(radiosnome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnpesqcli)
                        .addGap(18, 18, 18)
                        .addComponent(btnpesqsair)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioid)
                    .addComponent(radionome)
                    .addComponent(radiosnome))
                .addGap(18, 18, 18)
                .addComponent(txtpesqcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpesqcli)
                    .addComponent(btnpesqsair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioidActionPerformed
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radioidActionPerformed

    private void btnpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqcliActionPerformed
        // fazendo contagem de linhas
        int num = tblTabela.getRowCount();
        if (num == 0) {
            resposta = "";
            dispose();
            return;
        }

        for (int i = 0; i < num; i++) {
            if (tblTabela.isRowSelected(i)) {
                resposta = Ultilidades.objectToString(tblTabela.getValueAt(i, 0));
                
                dispose();
                return;
            }
        }
        resposta = Ultilidades.objectToString(tblTabela.getValueAt(0, 0));
                
                dispose();
    }//GEN-LAST:event_btnpesqcliActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // chamando metodo de preencher tabela   
        preencherTabela();
        txtpesqcli.requestFocusInWindow();

    }//GEN-LAST:event_formWindowOpened

    private void radionomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionomeActionPerformed

        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();

    }//GEN-LAST:event_radionomeActionPerformed

    private void radiosnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosnomeActionPerformed
        txtpesqcli.setText("");
        txtpesqcli.requestFocusInWindow();
        preencherTabela();
    }//GEN-LAST:event_radiosnomeActionPerformed

    private void txtpesqcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesqcliActionPerformed
        // pedindo para preencher a tabela
        preencherTabela();
    }//GEN-LAST:event_txtpesqcliActionPerformed

    private void btnpesqsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesqsairActionPerformed
        // Saindo
        resposta = "";
        dispose();
    }//GEN-LAST:event_btnpesqsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPesqCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPesqCliente dialog = new frmPesqCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgtipopesq;
    private javax.swing.JButton btnpesqcli;
    private javax.swing.JButton btnpesqsair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioid;
    private javax.swing.JRadioButton radionome;
    private javax.swing.JRadioButton radiosnome;
    private javax.swing.JTable tblTabela;
    private javax.swing.JTextField txtpesqcli;
    // End of variables declaration//GEN-END:variables
}
